version: '2'

services:

  kafka-zookeeper:
    image: confluentinc/cp-zookeeper:5.4.0
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  kafka-node:
    image: confluentinc/cp-kafka:5.4.0
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=kafka-zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - kafka-zookeeper